# Argoverse2 dataset configuration
data:
  data_root: /data0/dataset/preprocessed/argoverse/training
  dataset: argoverse
  scene_idx: 0
  start_timestep: 0
  end_timestep: -1
  preload_device: cuda
  pixel_source:
    type: datasets.argoverse.argoverse_sourceloader.ArgoversePixelSource
    cameras: [0, 1, 2]
    downscale_when_loading: [1, 1, 1]
    downscale: 1
    undistort: false
    test_image_stride: 0
    load_sky_mask: true
    load_dynamic_mask: false
    load_objects: true
    load_smpl: false
    sampler:
      buffer_downscale: 8
      buffer_ratio: 0.5
      start_enhance_weight: 3
  lidar_source:
    type: datasets.argoverse.argoverse_sourceloader.ArgoverseLiDARSource
    load_lidar: true
    only_use_top_lidar: false
    truncated_max_range: 80
    truncated_min_range: -2
    lidar_downsample_factor: 4
    lidar_percentile: 0.02
